TOL_TWO_PHASE_STABILITY_CONVERGENCE = 1e-8
TOL_TWO_PHASE_STABILITY_CONVERGENCE_TRIVIAL_SOLUTION = 1e-4
TOL_TWO_PHASE_FLASH_BISECTION_CONVERGENCE = 1e-13
TOL_TWO_PHASE_FLASH_CONVERGENCE = 1e-14
TOL_TWO_PHASE_FLASH_TRIVIAL_SOLUTION = 1e-09
TOL_SAT_PRESSURE = 1e-8
CONSTANT_R = 8.31